import 'package:bruig/plugin_system/canvas/model/procedural_effects.dart';
import 'package:bruig/plugin_system/canvas/model/procedural_layers.dart';
import 'package:bruig/plugin_system/canvas/model/procedural_light.dart';
import 'package:bruig/plugin_system/canvas/model/procedural_palettes.dart';
import 'package:bruig/plugin_system/canvas/model/procedural_rings.dart';
import 'package:bruig/plugin_system/canvas/model/procedural_spec.dart';
import 'package:flutter/painting.dart';

// background_looks.dart is the designed starting points for every style.
//
// A style on its own is one picture and a dozen settings, and finding the
// good versions of it is the work nobody wants to do first. A look is one of
// those good versions already found: chosen, it is the whole recipe -- the
// colours, the numbers, the effects -- and every setting is still there to
// carry on from.

/// BackgroundLook is one designed version of a style.
class BackgroundLook {
  final String name;
  final ProceduralSpec spec;
  const BackgroundLook(this.name, this.spec);
}

/// looksFor is [style]'s looks, in the order they are shown.
List<BackgroundLook> looksFor(ProceduralStyle style) =>
    (_looks ??= _build())[style] ?? const [];

/// withLook is [current] made into [look], keeping what belongs to the
/// document rather than to the design: how long a run of the movement is,
/// whether it moves, any pictures the rings were carrying, and the layers
/// laid over it -- unless the look is itself a stack of layers, when its
/// own come with it.
ProceduralSpec withLook(ProceduralSpec current, BackgroundLook look) {
  var s = look.spec;
  return s.copyWith(
    animated: current.animated || s.animated,
    passFrames: current.passFrames,
    loopTimes: current.loopTimes,
    loopGap: current.loopGap,
    pauseAt: current.pauseAt,
    pauseFor: current.pauseFor,
    pauseEase: current.pauseEase,
    // The layers over it are a design of their own, laid on whatever is
    // under them.
    layers: s.layers.isNotEmpty ? s.layers : current.layers,
    rings: s.style == ProceduralStyle.rings
        ? s.rings.copyWith(icons: current.rings.icons)
        : null,
  );
}

/// lookMatching is the look [spec] is, if it is still exactly one, for
/// showing which one is chosen.
BackgroundLook? lookMatching(ProceduralSpec spec) {
  var json = spec.toJson().toString();
  for (var look in looksFor(spec.style)) {
    if (withLook(spec, look).toJson().toString() == json) return look;
  }
  return null;
}

Map<ProceduralStyle, List<BackgroundLook>>? _looks;

/// _in is a palette by name. A misspelt one is a mistake here rather than
/// something to recover from, so it is not caught.
BackgroundPalette _in(String name) => paletteNamed(name)!;

BackgroundLook _look(
  String name,
  ProceduralStyle style,
  String palette, {
  double density = 0.5,
  double scale = 0.05,
  double intensity = 0.8,
  double variation = 0.5,
  double rotation = 0,
  double vignette = 0.25,
  int seed = 1,
  EffectsSpec effects = const EffectsSpec(),
  LightSpec light = const LightSpec(),
  Map<String, double> params = const {},
  RingSpec rings = const RingSpec(),
  MetalSpec metal = const MetalSpec(),
  PitchSport sport = PitchSport.football,
  String? glyphs,
  Color? base,
  Color? main,
  Color? accent,
  List<BackgroundLayer> layers = const [],
}) {
  var spec = _in(palette).on(ProceduralSpec(
    style: style,
    seed: seed,
    density: density,
    scale: scale,
    intensity: intensity,
    variation: variation,
    rotation: rotation,
    vignette: vignette,
    effects: effects,
    light: light,
    params: params,
    rings: rings,
    metal: metal,
    sport: sport,
    glyphs: glyphs ?? defaultGlyphs,
  ));
  return BackgroundLook(
      name,
      spec.copyWith(
        background: base,
        foreground: main,
        accent: accent,
        flatBackground: base != null,
        layers: layers,
      ));
}

/// _over is the look [name] of [style] as a layer.
BackgroundLayer _over(ProceduralStyle style, String name,
        {double opacity = 1,
        LayerBlend blend = LayerBlend.screen,
        EffectsSpec? effects}) =>
    BackgroundLayer(
      spec: () {
        var spec = _built[style]!.firstWhere((l) => l.name == name).spec;
        return effects == null ? spec : spec.copyWith(effects: effects);
      }(),
      opacity: opacity,
      blend: blend,
    );

/// _built is the looks without layers, which the ones with layers are
/// made from.
late Map<ProceduralStyle, List<BackgroundLook>> _built;

const _hex = "0123456789ABCDEF";
const _binary = "01";

Map<ProceduralStyle, List<BackgroundLook>> _build() {
  _built = _single();
  ProceduralStyle at(String n) =>
      ProceduralStyle.values.firstWhere((x) => x.name == n);
  // Stacks: a look with layers over it, each layer itself one of the looks
  // above.
  void add(String style, BackgroundLook look) => _built[at(style)]!.add(look);
  add(
      "gradientMesh",
      _look("Mesh and grid", at("gradientMesh"), "Midnight",
          intensity: 1,
          params: const {"meshKind": 1},
          effects: const EffectsSpec(grain: 0.2),
          layers: [
            _over(at("lineGrid"), "Isometric", opacity: 0.35),
          ]));
  add(
      "starfield",
      _look("Galaxy", at("starfield"), "Aurora",
          density: 0.7,
          intensity: 1,
          params: const {
            "nebula": 0.5
          },
          layers: [
            _over(at("gradientMesh"), "Northern lights",
                opacity: 0.6, blend: LayerBlend.add),
          ]));
  add(
      "lineGrid",
      _look("Synth night", at("lineGrid"), "Synthwave",
          scale: 0.05,
          intensity: 1,
          vignette: 0.3,
          params: const {"gridLayout": 2, "sun": 1, "major": 0, "weight": 1.6},
          effects: const EffectsSpec(glow: 1),
          layers: [
            _over(at("starfield"), "Deep space",
                opacity: 0.9,
                effects: const EffectsSpec(
                    glow: 0.4, clear: ClearArea.bottom, clearSize: 0.6)),
          ]));
  add(
      "starfield",
      _look("Chain in space", at("starfield"), "Midnight",
          density: 0.6,
          intensity: 1,
          params: const {"nebula": 0.8},
          effects: const EffectsSpec(glow: 0.4),
          layers: [
            _over(at("blockchain"), "Decred chain", blend: LayerBlend.normal),
          ]));
  add(
      "plain",
      _look("Sketchbook", at("plain"), "Paper",
          vignette: 0.15,
          effects: const EffectsSpec(grain: 0.3),
          layers: [
            _over(at("crosshatch"), "Pencil",
                opacity: 0.5, blend: LayerBlend.multiply),
          ]));
  return _built;
}

Map<ProceduralStyle, List<BackgroundLook>> _single() {
  const s = ProceduralStyle.values;
  ProceduralStyle at(String n) => s.firstWhere((x) => x.name == n);
  return {
    at("plain"): [
      _look("Deep blue", at("plain"), "Decred"),
      _look("Sunset", at("plain"), "Sunset", vignette: 0.15),
      _look("Paper", at("plain"), "Paper",
          vignette: 0.1, effects: const EffectsSpec(grain: 0.35)),
      _look("Film", at("plain"), "Graphite",
          vignette: 0.45, effects: const EffectsSpec(grain: 0.6)),
    ],
    at("gradientMesh"): [
      _look("Mesh", at("gradientMesh"), "Aurora",
          intensity: 1,
          vignette: 0.1,
          params: const {"meshKind": 1},
          effects: const EffectsSpec(grain: 0.25)),
      _look("Sunset mesh", at("gradientMesh"), "Sunset",
          intensity: 1,
          vignette: 0,
          seed: 3,
          params: const {"meshKind": 1, "points": 6, "warp": 0.7},
          effects: const EffectsSpec(grain: 0.2)),
      _look("Pastel mesh", at("gradientMesh"), "Pastel",
          intensity: 1,
          vignette: 0,
          seed: 8,
          params: const {"meshKind": 1, "softness": 0.7}),
      _look("Northern lights", at("gradientMesh"), "Aurora",
          density: 0.6,
          intensity: 0.9,
          vignette: 0.3,
          params: const {"meshKind": 2},
          effects: const EffectsSpec(blur: 0.08, grain: 0.15)),
      _look("Synthwave", at("gradientMesh"), "Synthwave",
          density: 0.35, intensity: 1, seed: 4),
      _look("Ember glow", at("gradientMesh"), "Ember",
          density: 0.3,
          intensity: 1,
          seed: 7,
          effects: const EffectsSpec(grain: 0.3)),
    ],
    at("bokeh"): [
      _look("City lights", at("bokeh"), "Sunset",
          density: 0.5,
          intensity: 0.9,
          params: const {"aperture": 1, "depth": 1},
          effects: const EffectsSpec(blur: 0.05)),
      _look("Underwater", at("bokeh"), "Ocean",
          density: 0.35,
          scale: 0.07,
          intensity: 0.8,
          effects: const EffectsSpec(focus: 0.6, focusY: 0.2)),
      _look("Gold dust", at("bokeh"), "Gold",
          density: 0.8,
          scale: 0.025,
          intensity: 1,
          variation: 0.8,
          params: const {"depth": 1},
          effects: const EffectsSpec(glow: 0.5)),
      _look("Lens", at("bokeh"), "Midnight",
          density: 0.4,
          scale: 0.06,
          intensity: 1,
          params: const {"aperture": 2, "rim": 0.9}),
      _look("Clear middle", at("bokeh"), "Neon",
          density: 0.6,
          intensity: 0.9,
          effects: const EffectsSpec(clear: ClearArea.centre, clearSize: 0.5)),
    ],
    at("flowWaves"): [
      _look("Silk", at("flowWaves"), "Midnight",
          intensity: 0.9,
          params: const {"waveKind": 1, "waves": 5},
          effects: const EffectsSpec(glow: 0.4)),
      _look("Flowing lines", at("flowWaves"), "Decred",
          intensity: 0.9,
          params: const {"waveKind": 2, "waves": 12, "twist": 0.5},
          effects: const EffectsSpec(glow: 0.5)),
      _look("Sunset silk", at("flowWaves"), "Sunset",
          intensity: 1,
          params: const {"waveKind": 1, "waves": 4, "thickness": 0.7},
          effects: const EffectsSpec(grain: 0.2)),
      _look("Ocean silk", at("flowWaves"), "Ocean",
          intensity: 1,
          seed: 5,
          params: const {
            "waveKind": 1,
            "waves": 8,
            "thickness": 0.25,
            "spread": 0.5
          },
          effects: const EffectsSpec(glow: 0.3)),
      _look("Neon flow", at("flowWaves"), "Neon",
          intensity: 1,
          params: const {"waveKind": 2, "waves": 8, "amplitude": 0.9},
          effects: const EffectsSpec(glow: 0.9, scanlines: 0.2)),
    ],
    at("rings"): [
      _look("Pulse", at("rings"), "Decred",
          rings: const RingSpec(count: 10, width: 0.006),
          effects: const EffectsSpec(glow: 0.8)),
      _look("Ripples", at("rings"), "Ocean",
          rings: const RingSpec(count: 18, width: 0.003),
          effects: const EffectsSpec(glow: 0.5)),
      _look("Target", at("rings"), "Comic",
          rings: const RingSpec(count: 7, width: 0.04), vignette: 0),
    ],
    at("starfield"): [
      _look("Nebula", at("starfield"), "Midnight",
          density: 0.6,
          intensity: 1,
          params: const {"nebula": 0.8},
          effects: const EffectsSpec(glow: 0.5)),
      _look("Deep space", at("starfield"), "Midnight",
          density: 0.6,
          intensity: 1,
          params: const {"shooting": 0.4},
          effects: const EffectsSpec(glow: 0.6)),
      _look("Aurora sky", at("starfield"), "Aurora",
          density: 0.8,
          intensity: 0.9,
          variation: 0.8,
          params: const {"nebula": 0.6, "spikes": 0.08},
          effects: const EffectsSpec(glow: 0.9, grain: 0.2)),
      _look("Warp speed", at("starfield"), "Midnight",
          density: 0.6,
          intensity: 1,
          params: const {"warp": 1},
          effects: const EffectsSpec(glow: 0.6)),
      _look("Warm stars", at("starfield"), "Ember",
          density: 0.4,
          intensity: 1,
          params: const {"nebula": 0.4},
          effects: const EffectsSpec(glow: 0.5)),
    ],
    at("dotGrid"): [
      _look("Tech dots", at("dotGrid"), "Decred",
          density: 0.9,
          scale: 0.02,
          intensity: 1,
          variation: 0,
          effects: const EffectsSpec(glow: 0.4)),
      _look("Paper dots", at("dotGrid"), "Paper",
          density: 1,
          scale: 0.015,
          intensity: 0.5,
          variation: 0,
          vignette: 0,
          params: const {"shading": 1}),
      _look("Ripple", at("dotGrid"), "Aurora",
          density: 1,
          scale: 0.02,
          intensity: 1,
          variation: 0,
          params: const {"shading": 2, "dotShape": 2, "dotSize": 0.16},
          effects: const EffectsSpec(glow: 0.6)),
      _look("Faded edge", at("dotGrid"), "Midnight",
          density: 1,
          scale: 0.025,
          intensity: 1,
          variation: 0.1,
          params: const {"layout": 1},
          effects: const EffectsSpec(focus: 1, focusSize: 0.05)),
      _look("Scoreboard", at("dotGrid"), "Ember",
          density: 0.7,
          scale: 0.02,
          intensity: 1,
          params: const {"dotKind": 1, "unlit": 1},
          effects: const EffectsSpec(glow: 0.6)),
      _look("Stage wall", at("dotGrid"), "Neon",
          density: 0.8,
          scale: 0.025,
          intensity: 1,
          variation: 0,
          params: const {"dotKind": 1},
          effects: const EffectsSpec(glow: 0.9, scanlines: 0.2)),
    ],
    at("lineGrid"): [
      _look("Retro grid", at("lineGrid"), "Synthwave",
          scale: 0.05,
          intensity: 1,
          vignette: 0.3,
          params: const {"gridLayout": 2, "sun": 1, "major": 0, "weight": 1.6},
          effects: const EffectsSpec(glow: 1)),
      _look("Blueprint", at("lineGrid"), "Blueprint",
          scale: 0.03, intensity: 0.9, vignette: 0.2),
      _look("Isometric", at("lineGrid"), "Midnight",
          scale: 0.035,
          intensity: 0.8,
          params: const {"gridLayout": 1, "major": 3},
          effects: const EffectsSpec(glow: 0.4, focus: 0.6)),
      _look("Graph paper", at("lineGrid"), "Snow",
          scale: 0.02, intensity: 0.7, vignette: 0, params: const {"major": 5}),
      _look("Neon floor", at("lineGrid"), "Neon",
          scale: 0.04,
          intensity: 1,
          params: const {"gridLayout": 2, "horizon": 0.35, "major": 0},
          effects: const EffectsSpec(glow: 1.2)),
      _look("Dark grid", at("lineGrid"), "Graphite",
          scale: 0.03,
          intensity: 0.6,
          effects: const EffectsSpec(clear: ClearArea.centre)),
    ],
    at("hexGrid"): [
      _look("Honeycomb", at("hexGrid"), "Gold",
          density: 0.75,
          scale: 0.04,
          intensity: 0.9,
          params: const {"hexStyle": 2, "gap": 0.06, "shading": 1}),
      _look("Shield", at("hexGrid"), "Decred",
          density: 0.3,
          scale: 0.03,
          intensity: 1,
          effects: const EffectsSpec(glow: 0.7, focus: 0.7)),
      _look("Hex tiles", at("hexGrid"), "Ocean",
          density: 0.5,
          scale: 0.035,
          intensity: 1,
          params: const {"hexStyle": 1, "gap": 0.12, "shading": 2}),
      _look("Light hex", at("hexGrid"), "Snow",
          density: 0.2, scale: 0.035, intensity: 0.7, vignette: 0),
      _look("Sci-fi panel", at("hexGrid"), "Graphite",
          density: 0.3,
          scale: 0.05,
          intensity: 1,
          accent: const Color(0xFF3CF2B0),
          params: const {"hexStyle": 2, "gap": 0.03},
          effects: const EffectsSpec(glow: 0.5, grain: 0.2)),
    ],
    at("circuit"): [
      _look("Mainboard", at("circuit"), "Matrix",
          density: 0.6,
          intensity: 0.9,
          params: const {"corners": 1, "chips": 0.5, "pulses": 0.4},
          effects: const EffectsSpec(glow: 0.5)),
      _look("Blueprint", at("circuit"), "Blueprint",
          density: 0.5,
          intensity: 0.8,
          vignette: 0.15,
          params: const {"pads": 1}),
      _look("Neon PCB", at("circuit"), "Neon",
          density: 0.8,
          intensity: 1,
          params: const {"corners": 1, "pulses": 0.6},
          effects: const EffectsSpec(glow: 1)),
      _look("Gold traces", at("circuit"), "Gold",
          density: 0.5,
          intensity: 0.9,
          params: const {"corners": 1, "chips": 0.3, "weight": 1.6},
          effects: const EffectsSpec(glow: 0.4, grain: 0.2)),
      _look("Square board", at("circuit"), "Decred",
          density: 0.6,
          intensity: 0.9,
          params: const {"chips": 0.6, "pulses": 0.5},
          effects: const EffectsSpec(glow: 0.4)),
    ],
    at("blockchain"): [
      _look("Decred chain", at("blockchain"), "Decred",
          scale: 0.06,
          intensity: 0.9,
          params: const {"mode": 0, "rows": 3},
          effects: const EffectsSpec(glow: 0.5)),
      _look("Chain in depth", at("blockchain"), "Decred",
          scale: 0.06,
          intensity: 0.95,
          params: const {"mode": 0, "rows": 4, "layout": 1},
          effects: const EffectsSpec(glow: 0.6, focus: 0.3)),
      _look("Into the distance", at("blockchain"), "Midnight",
          scale: 0.06,
          intensity: 1,
          params: const {"mode": 0, "rows": 1, "layout": 2, "pulses": 0.8},
          effects: const EffectsSpec(glow: 0.7)),
      _look("Global network", at("blockchain"), "Decred",
          density: 0.6,
          intensity: 1,
          params: const {"mode": 5, "pulses": 0.6},
          effects: const EffectsSpec(glow: 0.8)),
      _look("Hash pointers", at("blockchain"), "Blueprint",
          scale: 0.07,
          intensity: 0.9,
          vignette: 0.15,
          params: const {
            "mode": 0,
            "rows": 2,
            "blockShape": 1,
            "link": 4,
            "blockGap": 1.2
          }),
      _look("Node network", at("blockchain"), "Neon",
          density: 0.55,
          intensity: 0.9,
          params: const {"mode": 1, "nodeShape": 1, "hubs": 0.12},
          effects: const EffectsSpec(glow: 0.8)),
      _look("Ledger", at("blockchain"), "Matrix",
          scale: 0.05,
          density: 0.7,
          params: const {"mode": 2, "ledgerKind": 1, "columns": 3},
          effects: const EffectsSpec(glow: 0.4, scanlines: 0.25)),
      _look("Merkle proof", at("blockchain"), "Midnight",
          intensity: 0.9,
          params: const {"mode": 3, "levels": 4},
          effects: const EffectsSpec(glow: 0.6)),
      _look("Block city", at("blockchain"), "Synthwave",
          scale: 0.045,
          density: 0.85,
          params: const {"mode": 4, "fieldHeight": 0.6, "highlight": 0.25},
          effects: const EffectsSpec(glow: 0.6, focus: 0.5, focusY: 0.7)),
    ],
    at("rain"): [
      _look("Digital rain", at("rain"), "Matrix",
          density: 0.7,
          scale: 0.03,
          intensity: 1,
          params: const {"headGlow": 1},
          effects: const EffectsSpec(glow: 0.6)),
      _look("Binary", at("rain"), "Decred",
          density: 0.6,
          scale: 0.035,
          intensity: 1,
          glyphs: _binary,
          params: const {"glyphFont": 1},
          effects: const EffectsSpec(glow: 0.5)),
      _look("Hex stream", at("rain"), "Neon",
          density: 0.8,
          scale: 0.032,
          intensity: 0.9,
          glyphs: _hex,
          params: const {"glyphFont": 1, "direction": 1, "trail": 1.6},
          effects: const EffectsSpec(glow: 0.7, scanlines: 0.3)),
      _look("Hex cloud", at("rain"), "Decred",
          density: 0.4,
          intensity: 0.8,
          glyphs: _hex,
          params: const {"glyphFont": 1, "mode": 1},
          effects: const EffectsSpec(blur: 0.05)),
      _look("Binary dust", at("rain"), "Matrix",
          density: 0.7,
          scale: 0.03,
          glyphs: _binary,
          params: const {"glyphFont": 1, "mode": 1},
          effects: const EffectsSpec(focus: 0.8, glow: 0.4)),
      _look("Ink letters", at("rain"), "Paper",
          density: 0.3,
          scale: 0.06,
          intensity: 0.5,
          glyphs: "ABCDEFGHIJKLMNOPQRSTUVWXYZ&?!",
          vignette: 0,
          params: const {"glyphFont": 2, "mode": 1}),
    ],
    at("contours"): [
      _look("Topographic", at("contours"), "Paper",
          density: 0.6,
          intensity: 0.7,
          vignette: 0,
          params: const {"major": 5}),
      _look("Relief map", at("contours"), "Forest",
          density: 0.7,
          intensity: 1,
          vignette: 0.2,
          params: const {"contourKind": 1, "major": 4, "weight": 0.7}),
      _look("Night map", at("contours"), "Midnight",
          density: 0.7, intensity: 0.9, effects: const EffectsSpec(glow: 0.5)),
      _look("Heat map", at("contours"), "Ember",
          density: 0.8,
          intensity: 1,
          variation: 0.3,
          params: const {"contourKind": 1, "weight": 0.5},
          effects: const EffectsSpec(glow: 0.3)),
      _look("Ocean floor", at("contours"), "Ocean",
          density: 0.6,
          intensity: 0.9,
          params: const {"contourKind": 1, "major": 3}),
    ],
    at("flames"): [
      _look("Bonfire", at("flames"), "Ember",
          density: 0.6,
          intensity: 1,
          params: const {"flameKind": 1, "embers": 0.5},
          effects: const EffectsSpec(glow: 0.8)),
      _look("Blue flame", at("flames"), "Ocean",
          density: 0.5,
          intensity: 1,
          main: const Color(0xFF2C7CFF),
          accent: const Color(0xFFBFF5FF),
          params: const {"flameKind": 1, "height": 1.1},
          effects: const EffectsSpec(glow: 1)),
      _look("Inferno", at("flames"), "Ember",
          density: 0.9,
          intensity: 1,
          params: const {"flameKind": 1, "height": 1.4, "embers": 0.9},
          effects: const EffectsSpec(glow: 1.2, grain: 0.2)),
      _look("Comic fire", at("flames"), "Comic",
          density: 0.7,
          intensity: 1,
          vignette: 0,
          main: const Color(0xFFE6262E),
          accent: const Color(0xFFFFB000),
          base: const Color(0xFF111111)),
    ],
    at("halftone"): [
      _look("Comic", at("halftone"), "Comic",
          density: 0.6, scale: 0.02, intensity: 1, vignette: 0),
      _look("Comic fade", at("halftone"), "Comic",
          density: 0.7,
          scale: 0.025,
          intensity: 1,
          vignette: 0,
          params: const {"ink": 1}),
      _look("Pop art", at("halftone"), "Neon",
          density: 0.5,
          scale: 0.025,
          intensity: 1,
          vignette: 0,
          params: const {"ink": 2}),
      _look("Line screen", at("halftone"), "Blueprint",
          density: 0.6,
          scale: 0.02,
          intensity: 0.9,
          vignette: 0,
          params: const {"dotShape": 3, "ink": 2}),
      _look("Newsprint", at("halftone"), "Paper",
          density: 0.5,
          scale: 0.012,
          intensity: 0.9,
          vignette: 0,
          effects: const EffectsSpec(grain: 0.3)),
    ],
    at("speedLines"): [
      _look("Action", at("speedLines"), "Comic",
          density: 0.5,
          intensity: 1,
          vignette: 0,
          params: const {"aim": 1},
          effects: const EffectsSpec(clear: ClearArea.centre, clearSize: 0.25)),
      _look("Hyperspace", at("speedLines"), "Midnight",
          density: 0.8,
          intensity: 0.8,
          variation: 0.9,
          effects: const EffectsSpec(glow: 0.8)),
      _look("Rush", at("speedLines"), "Paper",
          density: 0.6,
          intensity: 0.9,
          vignette: 0,
          params: const {"burstKind": 1}),
      _look("Sunburst", at("speedLines"), "Sunset",
          density: 0.3, intensity: 0.5, variation: 0.2, vignette: 0.2),
    ],
    at("crosshatch"): [
      _look("Ink sketch", at("crosshatch"), "Paper",
          density: 0.8,
          scale: 0.02,
          intensity: 0.6,
          vignette: 0,
          params: const {"tone": 1, "wobble": 0.4}),
      _look("Engraving", at("crosshatch"), "Gold",
          density: 0.8, scale: 0.012, intensity: 0.6),
      _look("Pencil", at("crosshatch"), "Snow",
          density: 0.9,
          scale: 0.015,
          intensity: 0.5,
          vignette: 0,
          main: const Color(0xFF4A4F57),
          accent: const Color(0xFF2B2F35),
          params: const {"tone": 1, "wobble": 0.7},
          effects: const EffectsSpec(grain: 0.25)),
      _look("Chalk", at("crosshatch"), "Graphite",
          density: 0.4,
          scale: 0.025,
          intensity: 0.5,
          params: const {"wobble": 0.5},
          effects: const EffectsSpec(grain: 0.5)),
    ],
    at("splatter"): [
      _look("Ink splash", at("splatter"), "Paper",
          density: 0.3,
          intensity: 1,
          vignette: 0,
          params: const {"splatKind": 3}),
      _look("Neon splash", at("splatter"), "Neon",
          density: 0.5, intensity: 1, seed: 4, params: const {"splatKind": 3}),
      _look("Watercolour", at("splatter"), "Paper",
          density: 0.4,
          intensity: 1,
          vignette: 0,
          main: const Color(0xFF3B6FB6),
          accent: const Color(0xFFE07A5F),
          params: const {"splatKind": 4},
          effects: const EffectsSpec(grain: 0.25)),
      _look("Drips", at("splatter"), "Neon",
          density: 0.5, intensity: 1, params: const {"splatKind": 1}),
      _look("Spray paint", at("splatter"), "Graphite",
          density: 0.5,
          intensity: 1,
          accent: const Color(0xFFFF2A6D),
          main: const Color(0xFF05D9E8),
          params: const {"splatKind": 2},
          effects: const EffectsSpec(grain: 0.2)),
      _look("Gold leaf", at("splatter"), "Graphite",
          density: 0.25,
          intensity: 1,
          accent: const Color(0xFFE6C36A),
          main: const Color(0xFFB08A3A),
          seed: 3,
          params: const {"splatKind": 3},
          effects: const EffectsSpec(grain: 0.3)),
    ],
    at("metal"): [
      _look("Brushed steel", at("metal"), "Graphite",
          base: const Color(0xFF8A9099),
          main: const Color(0xFFE6EBF2),
          accent: const Color(0xFF8B4A24),
          vignette: 0.2,
          params: const {"finish": 1},
          metal: const MetalSpec(damage: 0)),
      _look("Chrome", at("metal"), "Graphite",
          base: const Color(0xFFB8C0CA),
          main: const Color(0xFFFFFFFF),
          accent: const Color(0xFF8B4A24),
          vignette: 0.15,
          params: const {"finish": 2},
          metal: const MetalSpec(shine: 0.9, damage: 0)),
      _look("Tread plate", at("metal"), "Graphite",
          base: const Color(0xFF8E959E),
          main: const Color(0xFFE6EBF2),
          accent: const Color(0xFF8B4A24),
          vignette: 0.2,
          params: const {"finish": 3},
          metal: const MetalSpec(shine: 0.6, damage: 0)),
      _look("Hammered copper", at("metal"), "Ember",
          base: const Color(0xFFB0643A),
          main: const Color(0xFFF2B98A),
          accent: const Color(0xFF3F7F6A),
          vignette: 0.2,
          params: const {"finish": 4},
          metal: const MetalSpec(shine: 0.7, damage: 0)),
      _look("Riveted panels", at("metal"), "Graphite",
          base: const Color(0xFF6E757D),
          main: const Color(0xFFC9D0D8),
          accent: const Color(0xFF8B3E1C),
          vignette: 0.25,
          params: const {"finish": 7},
          metal: const MetalSpec(rust: 0.2, damage: 0.3)),
      _look("Perforated", at("metal"), "Graphite",
          base: const Color(0xFF2A2D31),
          main: const Color(0xFF9AA3AD),
          accent: const Color(0xFF6B3A20),
          vignette: 0.2,
          params: const {"finish": 6},
          metal: const MetalSpec(shine: 0.5, damage: 0)),
      _look("Rusty sheet", at("metal"), "Graphite",
          base: const Color(0xFF7A7570),
          main: const Color(0xFFD9D4CC),
          accent: const Color(0xFF8B3E1C),
          params: const {"finish": 5},
          metal: const MetalSpec(rust: 0.6, damage: 0.4, roughness: 0.6)),
      _look("Gold", at("metal"), "Gold",
          base: const Color(0xFFB08A3A),
          main: const Color(0xFFFFF1C1),
          accent: const Color(0xFF5A3A12),
          params: const {"finish": 1},
          metal: const MetalSpec(shine: 0.75, damage: 0)),
    ],
    at("surface"): [
      _look("Paper", at("surface"), "Paper",
          vignette: 0.1,
          base: const Color(0xFFF2EBDD),
          main: const Color(0xFFB9A98A),
          accent: const Color(0xFF6D5C45),
          params: const {"surfaceKind": 0, "relief": 0.3}),
      _look("Laid paper", at("surface"), "Paper",
          vignette: 0.2,
          base: const Color(0xFFE9DFC8),
          main: const Color(0xFFA08C66),
          accent: const Color(0xFF5B4A33),
          params: const {"surfaceKind": 0, "laid": 1, "relief": 0.6}),
      _look("Concrete", at("surface"), "Graphite",
          density: 0.5,
          base: const Color(0xFFA7A6A1),
          main: const Color(0xFF6F6E69),
          accent: const Color(0xFFD9D7D0),
          params: const {"surfaceKind": 1, "relief": 0.6}),
      _look("Formwork", at("surface"), "Graphite",
          density: 0.4,
          base: const Color(0xFF8E8D88),
          main: const Color(0xFF55544F),
          accent: const Color(0xFFC9C7C0),
          params: const {"surfaceKind": 1, "panels": 1, "relief": 0.6}),
      _look("Oak", at("surface"), "Ember",
          density: 0.4,
          base: const Color(0xFFC08A52),
          main: const Color(0xFF6E4524),
          accent: const Color(0xFF3B2412),
          params: const {"surfaceKind": 2, "polish": 0.35}),
      _look("Floorboards", at("surface"), "Ember",
          density: 0.3,
          variation: 0.3,
          base: const Color(0xFF9C6A3C),
          main: const Color(0xFF4E2F17),
          accent: const Color(0xFF2A170A),
          params: const {"surfaceKind": 2, "planks": 1, "polish": 0.5}),
      _look("Marble", at("surface"), "Snow",
          density: 0.4,
          vignette: 0.1,
          base: const Color(0xFFF1F0EC),
          main: const Color(0xFF6F7378),
          accent: const Color(0xFFC9A55A),
          params: const {"surfaceKind": 3, "polish": 0.8}),
      _look("Black marble", at("surface"), "Graphite",
          density: 0.5,
          base: const Color(0xFF15161A),
          main: const Color(0xFFD9DCE2),
          accent: const Color(0xFFC9A55A),
          params: const {"surfaceKind": 3, "polish": 0.85}),
      _look("Carbon fibre", at("surface"), "Graphite",
          base: const Color(0xFF0B0C0E),
          main: const Color(0xFF6A7380),
          accent: const Color(0xFFFFFFFF),
          params: const {"surfaceKind": 4, "polish": 0.7, "relief": 0.6}),
      _look("Denim", at("surface"), "Ocean",
          base: const Color(0xFF0E1A2C),
          main: const Color(0xFF2E4D7A),
          accent: const Color(0xFFD6DCE4),
          params: const {"surfaceKind": 5, "weave": 1, "relief": 0.6}),
      _look("Linen", at("surface"), "Paper",
          variation: 0.8,
          base: const Color(0xFF8C826F),
          main: const Color(0xFFE2D8C3),
          accent: const Color(0xFFD4C9B0),
          params: const {"surfaceKind": 5, "relief": 0.5}),
      _look("Leather", at("surface"), "Ember",
          density: 0.5,
          base: const Color(0xFF6B3A1E),
          main: const Color(0xFF2E160A),
          accent: const Color(0xFFB07040),
          params: const {"surfaceKind": 6, "polish": 0.4, "relief": 0.6}),
    ],
    at("pitch"): [
      _look("Football", at("pitch"), "Forest",
          base: const Color(0xFF2E7D32),
          main: const Color(0xFFFFFFFF),
          accent: const Color(0xFF1D3F87),
          vignette: 0.15),
      _look("Tactics board", at("pitch"), "Graphite",
          base: const Color(0xFF1E2A22),
          main: const Color(0xFFE8F0EA),
          accent: const Color(0xFF7FD69B),
          vignette: 0.1,
          variation: 0,
          params: const {"surface": 3, "goals": 0}),
      _look("Half pitch", at("pitch"), "Forest",
          base: const Color(0xFF2E7D32),
          main: const Color(0xFFFFFFFF),
          accent: const Color(0xFF1D3F87),
          vignette: 0.1,
          params: const {"area": 1, "runs": 1}),
      _look("Stadium", at("pitch"), "Forest",
          base: const Color(0xFF2E7D32),
          main: const Color(0xFFFFFFFF),
          accent: const Color(0xFF1D3F87),
          vignette: 0.2,
          params: const {"view": 2, "surround": 1, "floodlights": 1}),
      _look("Isometric", at("pitch"), "Forest",
          base: const Color(0xFF3A8A3E),
          main: const Color(0xFFFFFFFF),
          accent: const Color(0xFF1D3F87),
          vignette: 0.1,
          params: const {"view": 1}),
      _look("Athletics", at("pitch"), "Forest",
          base: const Color(0xFF2E7D32),
          main: const Color(0xFFFFFFFF),
          accent: const Color(0xFF1D3F87),
          vignette: 0.1,
          params: const {"view": 1, "surround": 2}),
      _look("Futsal", at("pitch"), "Ocean",
          sport: PitchSport.futsal,
          base: const Color(0xFF2F6FA3),
          main: const Color(0xFFFFFFFF),
          accent: const Color(0xFF7FB342),
          vignette: 0.1),
      _look("Basketball", at("pitch"), "Ember",
          sport: PitchSport.basketball,
          base: const Color(0xFFD9A066),
          main: const Color(0xFFFFFFFF),
          accent: const Color(0xFF8E2A2A),
          vignette: 0.1),
      _look("NBA arena", at("pitch"), "Ember",
          sport: PitchSport.basketballNba,
          base: const Color(0xFFD9A066),
          main: const Color(0xFFFFFFFF),
          accent: const Color(0xFF1D428A),
          vignette: 0.2,
          params: const {"view": 2, "surround": 1, "tilt": 0.6}),
      _look("Tennis", at("pitch"), "Ocean",
          sport: PitchSport.tennis,
          base: const Color(0xFF3C638E),
          main: const Color(0xFFFFFFFF),
          accent: const Color(0xFF4F8A5B),
          vignette: 0.1),
      _look("Clay court", at("pitch"), "Ember",
          sport: PitchSport.tennis,
          base: const Color(0xFFC0623A),
          main: const Color(0xFFFFFFFF),
          accent: const Color(0xFFA9532F),
          vignette: 0.1,
          params: const {"surface": 6}),
      _look("Field hockey", at("pitch"), "Ocean",
          sport: PitchSport.hockey,
          base: const Color(0xFF2E7DB5),
          main: const Color(0xFFFFFFFF),
          accent: const Color(0xFFD9466B),
          vignette: 0.1),
      _look("Ice rink", at("pitch"), "Snow",
          sport: PitchSport.iceHockey,
          base: const Color(0xFFF2F6FA),
          main: const Color(0xFF1F4E9E),
          accent: const Color(0xFFC8102E),
          vignette: 0.05),
      _look("Rugby union", at("pitch"), "Forest",
          sport: PitchSport.rugby,
          base: const Color(0xFF2E7D32),
          main: const Color(0xFFFFFFFF),
          accent: const Color(0xFF8E2A2A),
          vignette: 0.1),
      _look("Rugby league", at("pitch"), "Forest",
          sport: PitchSport.rugbyLeague,
          base: const Color(0xFF2E7D32),
          main: const Color(0xFFFFFFFF),
          accent: const Color(0xFF1D3F87),
          vignette: 0.1),
      _look("Gridiron", at("pitch"), "Forest",
          sport: PitchSport.americanFootball,
          base: const Color(0xFF2E7D32),
          main: const Color(0xFFFFFFFF),
          accent: const Color(0xFF1D3F87),
          vignette: 0.15,
          params: const {"view": 2, "surround": 1, "tilt": 0.6}),
    ],
  };
}
